### ISSUE TITLE
Unique cards check

### ISSUE THREAD

**Issue by krisztoferkunc** [emileindik/poker-odds-machine#1]
Util.ts line 91:  splits the string wrong, which causes that we get throws in some cases, even if all the cards are different.
E.g. there is one player with cards '7d,Jd' and board cards are 'Qh,Kh,Kd'. The result is: 
`Error: Input cards must be unique. Invalid: 7d,,JdQ,h,K,h,K,d at validateInput (util.ts:95)`

**Comment by emileindik** [comment]
@krisztoferkunc Thanks for the bug report. 
```
Some people, when confronted with a problem, think "I know, I'll use regular expressions." Now they have two problems.
```

New fixed version is published!
